### ISSUE TITLE
Error while loading shared libraries: libdrd.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DavidYaonanZhu** [neemoh/sigma7#1]
I put the libdhd.so and libdrd.so inside /usr/lib, and catkin_make succeeded. But when I want to launch the node, it popt out: "error while loading shared libraries: libdrd.so.3: cannot open shared object file: No such file or directory"
Where should I put the shared libraries?

**Comment by neemoh** [comment]
Hi David, I believe this is not an issue of this package. Make sure you have correctly installed the Sigma libraries, they are in the system path and have correct permissions (Shared libraries must be executable...). Here you can find some info about static and shared libraries: https://www.tecmint.com/understanding-shared-libraries-in-linux/

**Comment by DavidYaonanZhu** [comment]
Thanks a lot! I renamed the libdrd.so.3.7.2 file to libdrd.so.3, and included it inside package lib folder with some modifications on Cmakefile. Thank you for the information.
